### ISSUE TITLE
https://lug.org.uk/lugs/scotland → 404

### ISSUE THREAD

**Issue by DougInAMug** [ScotLUG/scotlug.github.io#6]
Hi there,

I clicked on the link, mentioned on https://www.scotlug.org.uk/ and got a 'page not found'

**Comment by automatical** [comment]
This @DougInAMug for reporting.

It looks like lug.org.uk doesn't have this page anymore. I'll remove the link.

**Comment by automatical** [comment]
On further inspection, lug.org.uk appears to have a case sensitive url structure. This has been fixed in https://github.com/ScotLUG/scotlug.github.io/pull/7
